public class Cursos {   
    public String ingles;
    public String linguagemProgramacao;
    public String apex;
    public String adminSalesforce;
    
    public Cursos(String ingles, String linguagemProgramacao, String apex, String adminSalesforce) {
        this.ingles = ingles;
        this.linguagemProgramacao = linguagemProgramacao;
        this.apex = apex;
        this.adminSalesforce = adminSalesforce;
    }
}